VP Role Expansion and Addition of Marketing Officer
codersforcauses/cfc-constitution pull request #2
Opened 2020-03-05 15:19 UTC by innocentmm

See comimt details

2020-03-06 05:53 UTC, Drewbi commented on Constitution.md
> +Adopted by General Meeting **\*\*\*\***\*\***\*\*\*\***\_\_**\*\*\*\***\*\***\*\*\*\*** xx/xx/2020
What's going on here?

2020-03-06 05:56 UTC, Drewbi commented on Constitution.md
> +5.1 The annual subscription for ordinary membership shall be an absolute minimum of \$4.
We can do another PR for formatting

2020-03-06 06:22 UTC, innocentmm commented
Oh whoops, we haven’t had the AGM so I didn’t set a date but I don’t know what’s happening there otherwise

Kind regards,

Innocent.
________________________________
From: Drew Alexander <notifications@github.com>
Sent: Friday, March 6, 2020 1:56:43 PM
To: codersforcauses/cfc-constitution <cfc-constitution@noreply.github.com>
Cc: Eaglei <innocent.m@outlook.com>; Author <author@noreply.github.com>
Subject: Re: [codersforcauses/cfc-constitution] VP Role Expansion and Addition of Marketing Officer (#2)


@Drewbi commented on this pull request.

________________________________

In Constitution.md<https://github.com/codersforcauses/cfc-constitution/pull/2#discussion_r388725279>:

> @@ -58,7 +58,7 @@ Students enrolled at the University of Western Australia.

 **5. SUBSCRIPTIONS**

-5.1 The annual subscription for ordinary membership shall be an absolute minimum of $4.
+5.1 The annual subscription for ordinary membership shall be an absolute minimum of \$4.


We can do another PR for formatting

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/codersforcauses/cfc-constitution/pull/2?email_source=notifications&email_token=AK2AWP6D7VHV7VFYQGWECQLRGCGBXA5CNFSM4LCMG3HKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCYHTTXA#pullrequestreview-370096604>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AK2AWPYDVH2JXFZKXJCH4B3RGCGBXANCNFSM4LCMG3HA>.

2020-03-10 04:38 UTC, Drewbi requested changes
This doesn't really transfer the responsibilities of Client Officer onto VP it just replaces it with Marketing Officer.

2020-03-17 07:57 UTC, innocentmm commented
Changes have been made.....

2020-03-19 05:35 UTC, Drewbi approved these changes

2020-03-28 10:19 UTC, Drewbi approved these changes

2020-05-23 06:43 UTC, closed without merging